### ISSUE TITLE
9.1 물리 및 가상 주소 방식

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week05_Team2_malloc-lab#13]

**Comment by pkw-May** [comment]
https://github.com/KraftonJungle4th/Classroom4_Week05_Team2_malloc-lab/wiki/9.1-%EA%B0%80%EC%83%81%EC%A3%BC%EC%86%8C-%EB%AC%BC%EB%A6%AC%EC%A3%BC%EC%86%8C
