### ISSUE TITLE
find_fit (옵션: explicit 또는 seglist 방식)

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week05_Team2_malloc-lab#33]

**Comment by pkw-May** [comment]
https://github.com/KraftonJungle4th/Classroom4_Week05_Team2_malloc-lab/wiki/Explicit-&-Segregated-free-list-%EB%B0%A9%EB%B2%95%EB%A1%A0-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0

이곳에 오늘 진행한 explicit free list 개념 내용 정리해두었습니다.
