### ISSUE TITLE
동료학습

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week05_Team2_malloc-lab#4]
### 필수 확인 내용
- [x] #8
- [x] #9
- [x] #12
- [x] #10
- [x] #11
----
### 퀴즈 대비 내용
- [x] 데이터 세그먼트
- [x] demand-zero memory
- [x] #36
- [x] #37
- [x] #38
- [x] heap 정렬 (Do it! 알고리즘 교재 p.286~296)

**Comment by pkw-May** [comment]
모든 키워드에 대해,
동적할당기 구현과 관련하여 필요하다고 판단되는 부분만 체리픽하여
제가 이해할 수 있는 수준까지 정리하였습니다.

두분께 공유드리면서 수정 보완하고자 합니다.

- #8 
  - [가상메모리, 페이지](https://www.notion.so/9f2c7452142243649ad36438b4586c3b?pvs=4)

- #10 / #11 
  - [메모리 할당기 구현시 고려사항](https://www.notion.so/e6af64f96d994593a516acc4b156b1ee?pvs=4)

- #9 
  - [sbrk, brk](https://www.notion.so/system-call-aa4674f29d3f48c0b779544786c1c962?pvs=4)

**Comment by kugorang** [comment]
퀴즈 대비 내용은 다음주 월요일에 몰아서 개념 정리하기로 함
